# Generated by Django 3.0.5 on 2021-07-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexercise',
            name='is_collaborative',
            field=models.BooleanField(default=0, verbose_name='Collaboratif ?'),
        ),
    ]
