# Generated by Django 3.0.5 on 2021-09-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20210901_2155'),
        ('qcm', '0002_customexercise_is_collaborative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='group_parcours', to='group.Group'),
        ),
    ]
