# Generated by Django 3.0.5 on 2021-09-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0003_auto_20210917_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de verrouillage'),
        ),
    ]
