# Generated by Django 3.0.5 on 2021-09-19 18:15

from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0002_auto_20210907_1916'),
        ('account', '0005_student_ebep'),
        ('group', '0004_auto_20210919_1915'),
        ('qcm', '0004_auto_20210918_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('color', models.CharField(default='#00819F', max_length=255, verbose_name='Couleur')),
                ('is_share', models.BooleanField(default=0, verbose_name='Mutualisé ?')),
                ('is_publish', models.BooleanField(default=0, verbose_name='Publié ?')),
                ('is_favorite', models.BooleanField(default=1, verbose_name='Favori ?')),
                ('duration', models.PositiveIntegerField(blank=True, default=2, verbose_name='Temps de chargement (min.)')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='A partir de')),
                ('stop', models.DateTimeField(blank=True, null=True, verbose_name='Date de verrouillage')),
                ('vignette', models.ImageField(blank=True, default='', upload_to=qcm.models.vignette_directory_path, verbose_name="Vignette d'accueil")),
                ('ranking', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('author', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_folders', to='account.Teacher', verbose_name='Auteur')),
                ('coteachers', models.ManyToManyField(blank=True, related_name='coteacher_folders', to='account.Teacher', verbose_name='Enseignant en co-animation')),
                ('groups', models.ManyToManyField(blank=True, related_name='group_folders', to='group.Group')),
                ('level', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_folders', to='socle.Level')),
                ('parcours', models.ManyToManyField(blank=True, related_name='folders', to='qcm.Parcours')),
                ('students', models.ManyToManyField(blank=True, related_name='students_folders', to='account.Student', verbose_name='Elèves')),
                ('subject', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_folders', to='socle.Subject', verbose_name='Enseignement')),
                ('teacher', models.ForeignKey(blank=True, default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_folders', to='account.Teacher')),
            ],
        ),
    ]
