# Generated by Django 3.0.5 on 2021-09-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0006_auto_20210919_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_trash',
            field=models.BooleanField(default=0, editable=False, verbose_name='Poubelle ?'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='is_trash',
            field=models.BooleanField(default=0, editable=False, verbose_name='Poubelle ?'),
        ),
    ]
