# Generated by Django 3.0.5 on 2021-09-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_student_ebep'),
        ('qcm', '0008_folder_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='students', to='account.Student'),
        ),
    ]
