# Generated by Django 3.0.5 on 2021-09-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_student_ebep'),
        ('qcm', '0011_auto_20210919_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='folders', to='account.Student'),
        ),
    ]
