# Generated by Django 3.0.5 on 2021-10-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20210919_1915'),
        ('account', '0005_student_ebep'),
        ('qcm', '0012_auto_20210921_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_individualisation', to='group.Group')),
                ('relationship', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_individualisation', to='qcm.Relationship')),
                ('student', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_individualisation', to='account.Student')),
            ],
        ),
    ]
