# Generated by Django 3.0.5 on 2021-10-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0014_blacklist_customexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='group',
        ),
    ]
