# Generated by Django 3.0.5 on 2021-10-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0006_auto_20211006_2229'),
        ('qcm', '0016_auto_20211002_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='courses', to='qcm.Folder', verbose_name='Attribuer aux dossiers'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='socle.Level', verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='socle.Subject', verbose_name='Enseignement'),
        ),
    ]
