# Generated by Django 3.0.5 on 2021-12-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0021_auto_20211027_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='customanswerbystudent',
            name='is_reading',
            field=models.BooleanField(default=0, editable=False),
        ),
    ]
