# Generated by Django 3.0.5 on 2021-12-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0006_auto_20211006_2229'),
        ('qcm', '0022_customanswerbystudent_is_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexercise',
            name='is_autocorrection',
            field=models.BooleanField(default=0, verbose_name='Autocorrection ?'),
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(verbose_name='Critère')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterions', to='socle.Knowledge', verbose_name='Thème')),
                ('level', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='criterions', to='socle.Level', verbose_name='Niveau')),
                ('skill', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='criterions', to='socle.Skill', verbose_name='Compétences')),
                ('subject', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterions', to='socle.Subject', verbose_name='Enseignement')),
            ],
        ),
        migrations.AddField(
            model_name='customexercise',
            name='criterions',
            field=models.ManyToManyField(blank=True, related_name='customexercises', to='qcm.Criterion'),
        ),
    ]
