# Generated by Django 3.0.5 on 2021-12-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0006_auto_20211006_2229'),
        ('qcm', '0023_auto_20211218_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='knowledge',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterions', to='socle.Knowledge', verbose_name='Thème'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='level',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterions', to='socle.Level', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='skill',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterions', to='socle.Skill', verbose_name='Compétences'),
        ),
    ]
