# Generated by Django 3.0.5 on 2021-12-18 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_teacher_is_contact'),
        ('qcm', '0024_auto_20211218_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('criterion', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='autopositions', to='qcm.Criterion')),
                ('customexercise', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='autopositions', to='qcm.Customexercise')),
                ('parcours', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='autopositions', to='qcm.Parcours')),
                ('student', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='autopositions', to='account.Student')),
            ],
        ),
    ]
