# Generated by Django 3.0.5 on 2021-12-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0025_autoposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcours',
            name='folder_parcours',
        ),
        migrations.RemoveField(
            model_name='parcours',
            name='is_folder',
        ),
        migrations.RemoveField(
            model_name='parcours',
            name='is_leaf',
        ),
        migrations.RemoveField(
            model_name='parcours',
            name='leaf_parcours',
        ),
    ]
