# Generated by Django 3.0.5 on 2022-01-16 12:45

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0026_auto_20211219_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='audiofile',
            field=models.FileField(blank=True, default='', upload_to=qcm.models.audio_directory_path, verbose_name='Fichier Audio'),
        ),
    ]
