# Generated by Django 3.0.5 on 2022-07-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0028_parcours_is_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='document_id',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='type_id',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
