# Generated by Django 3.0.5 on 2022-07-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0029_auto_20220720_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='is_sequence',
            field=models.BooleanField(default=0, editable=False, verbose_name="Séquence d'apprentissage ?"),
        ),
    ]
