# Generated by Django 3.0.5 on 2022-08-24 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_adhesion_year'),
        ('qcm', '0032_auto_20220824_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='teacher',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='demand', to='account.Teacher'),
        ),
    ]
