# Generated by Django 3.0.5 on 2021-08-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210818_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='civilite',
            field=models.CharField(blank=True, choices=[('Mme', 'Mme'), ('M.', 'M.')], default='Mme', max_length=10, verbose_name='Civilité'),
        ),
    ]
