# Generated by Django 3.0.5 on 2021-09-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210823_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ebep',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
