# Generated by Django 3.0.5 on 2021-10-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20211003_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='helping',
        ),
    ]
