# Generated by Django 3.0.5 on 2021-11-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_teacher_helping'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gar_token',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
