# Generated by Django 3.0.5 on 2021-11-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_gar_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gar_token',
        ),
    ]
