# Generated by Django 3.0.5 on 2021-11-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_user_gar_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_contact',
            field=models.BooleanField(default=0, verbose_name='Permettre aux élèves de me contacter ?'),
        ),
    ]
