# Generated by Django 3.0.5 on 2021-11-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_teacher_is_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_contact',
        ),
    ]
