# Generated by Django 3.0.5 on 2022-02-08 14:22

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_teacher_is_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=account.models.avatar_directory_path, verbose_name='avatar')),
                ('level', models.PositiveSmallIntegerField(choices=[(50, 1), (70, 2), (85, 3)])),
                ('adult', models.BooleanField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to=account.models.avatar_directory_path, verbose_name='avatar'),
        ),
    ]
