# Generated by Django 3.0.5 on 2022-03-13 18:05

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20220208_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=account.models.background_directory_path, verbose_name='background')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, default='', null=True, upload_to=account.models.background_directory_path, verbose_name='background'),
        ),
    ]
