# Generated by Django 3.0.5 on 2022-03-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0006_auto_20211006_2229'),
        ('account', '0015_auto_20220313_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion',
            name='levels',
            field=models.ManyToManyField(blank=True, editable=False, related_name='adhesions', to='socle.Level'),
        ),
        migrations.AddField(
            model_name='adhesion',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='adhesions', to='account.Student'),
        ),
    ]
