# Generated by Django 3.0.5 on 2022-03-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20220328_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adhesion',
            old_name='code',
            new_name='chrono',
        ),
    ]
