# Generated by Django 3.0.5 on 2022-05-04 15:05

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0006_auto_20211006_2229'),
        ('account', '0017_auto_20220328_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhesion',
            name='children',
        ),
        migrations.RemoveField(
            model_name='adhesion',
            name='chrono',
        ),
        migrations.RemoveField(
            model_name='adhesion',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='adhesion',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='adhesion',
            name='file',
        ),
        migrations.RemoveField(
            model_name='adhesion',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='adhesion',
            name='students',
        ),
        migrations.RemoveField(
            model_name='adhesion',
            name='user',
        ),
        migrations.AddField(
            model_name='adhesion',
            name='level',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to='socle.Level'),
        ),
        migrations.AddField(
            model_name='adhesion',
            name='start',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='adhesion',
            name='stop',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='adhesion',
            name='student',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to='account.Student'),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6, verbose_name='Montant'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrono', models.CharField(editable=False, max_length=50, verbose_name='Chrono')),
                ('file', models.FileField(blank=True, default='', editable=False, null=True, upload_to=account.models.file_directory_path, verbose_name='fichier')),
                ('chro', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Chrono')),
                ('adhesions', models.ManyToManyField(blank=True, editable=False, related_name='factures', to='account.Adhesion')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
