# Generated by Django 3.0.5 on 2022-05-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20220504_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='chro',
        ),
    ]
