# Generated by Django 3.0.5 on 2022-05-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_facture_chro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhesion',
            name='duration',
        ),
    ]
