# Generated by Django 3.0.5 on 2022-05-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_adhesion_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
