# Generated by Django 3.0.5 on 2022-07-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20220505_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='orderID',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Numéro de paiement donné par Paypal'),
        ),
        migrations.AddField(
            model_name='parent',
            name='periodicity',
            field=models.PositiveIntegerField(default=14, verbose_name='Périodicité ? En nombre de jours'),
        ),
    ]
