# Generated by Django 3.0.5 on 2022-07-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20220709_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='teachers', to='account.Student'),
        ),
    ]
