# Generated by Django 3.0.5 on 2022-07-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_teacher_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_lesson',
            field=models.BooleanField(default=0, verbose_name='Propose des cours ?'),
        ),
    ]
