# Generated by Django 3.0.5 on 2022-08-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20220731_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion',
            name='year',
            field=models.PositiveIntegerField(default=2021, editable=False),
        ),
    ]
