# Generated by Django 3.0.5 on 2021-11-14 10:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='audioanswer',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='audiohelper',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='imagefile',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='imagefileanswer',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='imagefilehelper',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='video',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='videoanswer',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='videohelper',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Réponse attendu'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='helper',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Aide proposée'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Question écrite'),
        ),
    ]
