# Generated by Django 3.0.5 on 2021-11-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_auto_20211114_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercard',
            name='flashpack',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answercards', to='flashcard.Flashpack'),
        ),
    ]
