# Generated by Django 3.0.5 on 2021-11-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_answercard_flashpack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answercard',
            name='is_correct',
        ),
    ]
