# Generated by Django 3.0.5 on 2021-11-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_remove_answercard_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercard',
            name='weight',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
