# Generated by Django 3.0.5 on 2021-11-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_auto_20211117_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='sizea',
            field=models.PositiveIntegerField(choices=[(16, '16'), (24, '24'), (32, '32'), (40, '40'), (48, '48'), (56, '56')], default=40, verbose_name='Taille de police'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='size',
            field=models.PositiveIntegerField(choices=[(16, '16'), (24, '24'), (32, '32'), (40, '40'), (48, '48'), (56, '56')], default=40, verbose_name='Taille de police'),
        ),
    ]
