# Generated by Django 3.0.5 on 2021-11-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0006_auto_20211118_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='sizeh',
            field=models.PositiveIntegerField(choices=[(16, '16'), (24, '24'), (32, '32'), (40, '40'), (48, '48'), (56, '56')], default=40, verbose_name='Taille de police'),
        ),
    ]
