# Generated by Django 3.0.5 on 2021-11-27 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0006_auto_20211006_2229'),
        ('flashcard', '0009_auto_20211120_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='waiting',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='socle.Waiting'),
        ),
    ]
