# Generated by Django 3.0.5 on 2021-11-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0010_auto_20211127_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashpack',
            name='interslide',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='is_validate',
            field=models.BooleanField(default=1, verbose_name="Validée par l'enseignant ?"),
        ),
        migrations.AddField(
            model_name='flashpack',
            name='is_creative',
            field=models.BooleanField(default=0, verbose_name='Création par les élèves de flashCard ?'),
        ),
    ]
