# Generated by Django 3.0.5 on 2021-11-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_teacher_is_contact'),
        ('flashcard', '0011_auto_20211128_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashpack',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='flashpacks', to='account.Student'),
        ),
    ]
