# Generated by Django 3.0.5 on 2021-11-28 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcard', '0012_flashpack_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='authors',
            field=models.ManyToManyField(blank=True, editable=False, related_name='flashcards', to=settings.AUTH_USER_MODEL),
        ),
    ]
