# Generated by Django 3.0.5 on 2021-11-28 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_teacher_is_contact'),
        ('flashcard', '0013_flashcard_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercard',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Madeflashpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('flashpack', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='madeflashpack', to='flashcard.Flashpack')),
                ('student', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='madeflashpack', to='account.Student')),
            ],
        ),
    ]
