# Generated by Django 3.0.5 on 2021-11-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0014_auto_20211128_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercard',
            name='answers',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
