# Generated by Django 3.0.5 on 2021-11-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0015_answercard_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercard',
            name='rappel',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
