# Generated by Django 3.0.5 on 2021-12-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0006_auto_20211006_2229'),
        ('flashcard', '0016_answercard_rappel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='is_validate',
            field=models.BooleanField(default=1, verbose_name="Flashcard validée par l'enseignant ?"),
        ),
        migrations.AlterField(
            model_name='flashpack',
            name='themes',
            field=models.ManyToManyField(related_name='flashpacks', to='socle.Theme'),
        ),
    ]
