# Generated by Django 3.0.5 on 2021-12-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0018_commentflashcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentflashcard',
            name='comment',
            field=models.TextField(verbose_name='Commentaire'),
        ),
    ]
