# Generated by Django 3.0.5 on 2021-12-03 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_teacher_is_contact'),
        ('flashcard', '0019_auto_20211203_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentflashcard',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='account.Teacher'),
        ),
    ]
