# Generated by Django 3.0.5 on 2021-12-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0020_auto_20211203_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentflashcard',
            name='flashpack',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='flashcard.Flashpack'),
        ),
    ]
