# Generated by Django 3.0.5 on 2021-12-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0022_remove_commentflashcard_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashpack',
            name='is_creative',
            field=models.BooleanField(default=0, verbose_name='Création de flashCard par les élèves ?'),
        ),
        migrations.AlterField(
            model_name='flashpack',
            name='stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
    ]
