# Generated by Django 3.0.5 on 2022-01-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0023_auto_20211212_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_publish',
            field=models.BooleanField(default=1, verbose_name='Publié ?'),
        ),
        migrations.AddField(
            model_name='flashpack',
            name='is_global',
            field=models.BooleanField(default=0, verbose_name='Flashpack annuel ?'),
        ),
    ]
