# Generated by Django 3.0.5 on 2022-01-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0025_auto_20220130_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_globalset',
            field=models.BooleanField(default=1, verbose_name='Contenue dans le flashpack annuel ?'),
        ),
    ]
