# Generated by Django 3.0.5 on 2022-01-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0026_flashcard_is_globalset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titre'),
        ),
    ]
