# Generated by Django 3.0.5 on 2022-02-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0027_auto_20220131_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashpack',
            name='is_inclusion',
            field=models.BooleanField(default=1, verbose_name='Inclusion automatique ?'),
        ),
    ]
