# Generated by Django 3.0.5 on 2022-02-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0006_auto_20211006_2229'),
        ('flashcard', '0028_flashpack_is_inclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='theme',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='socle.Theme'),
        ),
        migrations.AlterField(
            model_name='flashpack',
            name='is_inclusion',
            field=models.BooleanField(default=0, verbose_name='Inclusion automatique des cartes ?'),
        ),
    ]
