# Generated by Django 3.0.5 on 2021-06-23 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('town', models.CharField(default='', max_length=255, verbose_name='ville')),
                ('code_acad', models.CharField(default='999efe', max_length=255, verbose_name='Code UAI')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('zip_code', models.CharField(blank=True, default='99999', max_length=255, verbose_name='Code postal')),
                ('get_seconde_to_comp', models.BooleanField(default=0, editable=False)),
                ('nbstudents', models.PositiveIntegerField(default=500, verbose_name="Nombre d'élèves")),
                ('is_active', models.BooleanField(default=0, editable=False)),
                ('gar', models.BooleanField(default=0, verbose_name='Connexion via le GAR souhaitée')),
                ('country', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='school', related_query_name='school', to='school.Country', verbose_name='Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.PositiveIntegerField(default=50, verbose_name='Seuil 1 : NA à ECA')),
                ('medium', models.PositiveIntegerField(default=70, verbose_name='Seuil 2 : ACE à acquis')),
                ('up', models.PositiveIntegerField(default=85, verbose_name='Seuil 3 : acquis à dépassé')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='aptitude', to='school.School')),
            ],
        ),
    ]
