# Generated by Django 3.0.5 on 2021-07-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='rythme',
            field=models.BooleanField(default=0, verbose_name='Rythme'),
        ),
    ]
