# Generated by Django 3.0.5 on 2021-07-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_rythme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='rythme',
            field=models.BooleanField(default=1, verbose_name='Rythme'),
        ),
    ]
