# Generated by Django 3.0.5 on 2021-06-23 18:28

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('socle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Nom*')),
                ('color', models.CharField(blank=True, default='#46119c', max_length=255, null=True, verbose_name='Couleur*')),
                ('assign', models.BooleanField(default=1)),
                ('suiviparent', models.BooleanField(default=0)),
                ('studentprofile', models.BooleanField(default=0)),
                ('lock', models.BooleanField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='socle.Level', verbose_name='Niveau*')),
                ('students', models.ManyToManyField(blank=True, related_name='students_to_group', to='account.Student', verbose_name='Élèves*')),
                ('subject', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_group', to='socle.Subject', verbose_name='Matière*')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='account.Teacher', verbose_name='Enseignant*')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sharing_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField(default=0)),
                ('group', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_sharingteacher', to='group.Group')),
                ('teacher', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_sharingteacher', to='account.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, editable=False, related_name='teacher_group', through='group.Sharing_group', to='account.Teacher'),
        ),
    ]
