# Generated by Django 3.0.5 on 2021-08-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='recuperation',
            field=models.BooleanField(default=0),
        ),
    ]
