# Generated by Django 3.0.5 on 2021-09-01 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0001_initial'),
        ('school', '0003_auto_20210718_1034'),
        ('group', '0002_group_recuperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='school',
            field=models.ForeignKey(blank=True, default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_group', to='school.School'),
        ),
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='socle.Level', verbose_name='Niveau*'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_group', to='socle.Subject', verbose_name='Matière*'),
        ),
    ]
