# Generated by Django 3.0.5 on 2021-09-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20210901_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='studentprofile',
            field=models.BooleanField(default=1),
        ),
    ]
