# Generated by Django 3.0.5 on 2022-08-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20220820_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='formule_id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'autonomie'), (2, 'ADAPTATIF et Perso')], default=1),
        ),
    ]
