# Generated by Django 3.0.5 on 2021-07-25 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_holidaybook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plancomptable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='code')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
            ],
        ),
        migrations.AddField(
            model_name='accounting',
            name='is_paypal',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='forme',
            field=models.CharField(blank=True, choices=[('FACTURE', 'FACTURE'), ('AVOIR', 'AVOIR')], default='FACTURE', max_length=255, verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_accontings', to='association.Plancomptable', verbose_name='Plan comptable'),
        ),
    ]
