# Generated by Django 3.0.5 on 2021-07-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_auto_20210725_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plancomptable',
            old_name='nom',
            new_name='name',
        ),
    ]
