# Generated by Django 3.0.5 on 2021-07-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_auto_20210725_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='tp',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
