# Generated by Django 3.0.5 on 2021-07-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0005_accounting_tp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='plan',
            field=models.ForeignKey(blank=True, default=17, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_accontings', to='association.Plancomptable', verbose_name='Plan comptable'),
        ),
    ]
