# Generated by Django 3.0.5 on 2021-09-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_auto_20210727_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_display', models.PositiveIntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=2021, verbose_name='Année')),
            ],
        ),
    ]
