# Generated by Django 3.0.5 on 2021-09-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_active_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Active_year',
            new_name='Activeyear',
        ),
        migrations.RenameField(
            model_name='activeyear',
            old_name='is_display',
            new_name='year',
        ),
    ]
