# Generated by Django 3.0.5 on 2021-09-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0008_auto_20210906_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeyear',
            name='year',
            field=models.PositiveIntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=2021, verbose_name='Année'),
        ),
    ]
