# Generated by Django 3.0.5 on 2021-09-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0013_auto_20210916_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounting',
            old_name='acting',
            new_name='date_payment',
        ),
    ]
