# Generated by Django 3.0.5 on 2022-08-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0015_auto_20211009_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeyear',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='Année active'),
        ),
        migrations.AddField(
            model_name='activeyear',
            name='solde',
            field=models.IntegerField(default=0, verbose_name="Résultat de l'exercice précédent"),
        ),
        migrations.AlterField(
            model_name='activeyear',
            name='year',
            field=models.PositiveIntegerField(choices=[(2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026'), (2026, '2026-2027')], default=2021, verbose_name="Année de l'exercice"),
        ),
    ]
