# Generated by Django 3.0.5 on 2021-06-23 18:28

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('socle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Sacado', 'Sacado'), ('Pédagogie et Didactique', 'Pédagogie et Didactique'), ('Geogebra', 'Geogebra'), ('Python', 'Python'), ('Jeu et concours', 'Jeu et concours')], max_length=100, verbose_name='Catégorie')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Objet')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=1, verbose_name='Afficher la communication ?')),
                ('solve', models.BooleanField(default=0, verbose_name='Résolu ?')),
                ('nb_display', models.PositiveIntegerField(default=0, editable=False)),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_discussion', to='socle.Subject')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_discussion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Texte')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_message', to='sendmail.Discussion')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Objet')),
                ('texte', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Texte')),
                ('today', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_email', to=settings.AUTH_USER_MODEL)),
                ('receivers', models.ManyToManyField(blank=True, related_name='receiver_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Objet')),
                ('texte', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Texte')),
                ('today', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=1, verbose_name='Afficher la communication ?')),
                ('teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_communication', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, editable=False, related_name='teachers_communication', to='account.Teacher')),
            ],
        ),
    ]
