# Generated by Django 3.0.5 on 2022-08-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='solve',
            new_name='is_solve',
        ),
    ]
