# Generated by Django 3.0.5 on 2022-08-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_auto_20220820_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='category',
            field=models.CharField(blank=True, choices=[('Sacado', 'Sacado Académie'), ('Pédagogie et Didactique', 'Pédagogie et Didactique'), ('Geogebra', 'Geogebra'), ('Python', 'Python'), ('Autres', 'Autres')], max_length=100, verbose_name='Catégorie'),
        ),
    ]
