# Generated by Django 3.0.5 on 2021-06-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('adhesion', models.CharField(default='', max_length=255, verbose_name='Adhesion')),
                ('price', models.CharField(default='', max_length=255, verbose_name='Montant')),
                ('is_family', models.BooleanField(default=0, verbose_name='Forfait famille ?')),
                ('nb_month', models.PositiveIntegerField(default=1, verbose_name='Nombre de mois')),
            ],
        ),
    ]
