# Generated by Django 3.0.5 on 2021-07-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formule',
            name='adhesion',
            field=models.CharField(choices=[('Mensuelle', 'Mensuelle'), ('Trimestrielle', 'Trimestrielle'), ('Annuelle', 'Annuelle')], default='', max_length=255, verbose_name='Adhésion'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='name',
            field=models.CharField(choices=[('Autonomie', 'Autonomie'), ('Accompagnement', 'Accompagnement')], max_length=255, verbose_name='Nom'),
        ),
    ]
