# Generated by Django 3.0.5 on 2021-09-13 09:47

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import setup.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup', '0002_auto_20210721_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre')),
                ('is_publish', models.BooleanField(default=0, verbose_name='Publié ?')),
                ('date_time', models.DateTimeField(verbose_name='Date/heure')),
                ('imagefile', models.ImageField(blank=True, default='', null=True, upload_to=setup.models.webinaire_image_directory_path, verbose_name='Image')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('topic', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Remarques')),
                ('duration', models.PositiveIntegerField(blank=True, choices=[(20, 20), (30, 30), (40, 40), (50, 50), (60, 60)], default=0, null=True, verbose_name='Durée')),
                ('users', models.ManyToManyField(blank=True, related_name='webinaires', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
            ],
        ),
    ]
