# Generated by Django 3.0.5 on 2021-07-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
    ]
