# Generated by Django 3.0.5 on 2021-07-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_remove_question_themeeee'),
    ]


    operations = [
        migrations.AddField(
            model_name='quizz',
            name='is_archive',
            field=models.BooleanField(default=0, verbose_name='Archivé ?'),
        ),
    ]
