# Generated by Django 3.0.5 on 2021-07-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20210727_1136'),
    ]


    operations = [
        migrations.AlterField(
            model_name='diaporama',
            name='is_archive',
            field=models.BooleanField(default=0, editable=False, verbose_name='Archivé ?'),
        ),
    ]
