# Generated by Django 3.0.5 on 2021-08-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_auto_20210729_1422'),
    ]



    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='is_result',
            field=models.BooleanField(default=0, verbose_name='Afficher les réponses ?'),
        ),
    ]
