# Generated by Django 3.0.5 on 2021-09-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0002_customexercise_is_collaborative'),
        ('tool', '0007_auto_20210823_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='exercises',
            field=models.ManyToManyField(blank=True, editable=False, related_name='tools', to='qcm.Exercise', verbose_name='Outils inclusifs'),
        ),
    ]
