# Generated by Django 3.0.5 on 2021-09-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_tool_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_ebep',
            field=models.BooleanField(default=0, verbose_name='Outils EBEP ?'),
        ),
    ]
