# Generated by Django 3.0.5 on 2021-10-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0016_auto_20211002_1650'),
        ('tool', '0009_tool_is_ebep'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='quizz', to='qcm.Folder'),
        ),
    ]
