# Generated by Django 3.0.5 on 2022-02-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0013_auto_20211212_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='is_numeric',
            field=models.BooleanField(default=0, verbose_name='Type de passation'),
        ),
    ]
