# Generated by Django 3.0.5 on 2022-04-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0016_quizz_is_result_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hauteur'),
        ),
        migrations.AddField(
            model_name='question',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Largeur'),
        ),
    ]
