# Generated by Django 3.0.5 on 2022-07-29 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='name')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'calendar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('notification', models.BooleanField(blank=True, default=False, verbose_name='Notification?')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('display', models.BooleanField(default=0, verbose_name='Publication')),
                ('color', models.CharField(default='#00819F', max_length=50, verbose_name='color')),
                ('calendar', models.ManyToManyField(blank=True, to='lesson.Calendar', verbose_name='Calendrier')),
                ('users', models.ManyToManyField(blank=True, default='', related_name='events_with', related_query_name='events_with', to=settings.AUTH_USER_MODEL, verbose_name='Partagée avec')),
            ],
            options={
                'verbose_name': 'event',
                'ordering': ['start', 'end'],
            },
        ),
    ]
