# Generated by Django 3.0.5 on 2022-07-29 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, default='', related_name='events', related_query_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Partagée avec'),
        ),
    ]
