# Generated by Django 3.0.5 on 2022-07-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20220729_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='url'),
        ),
    ]
