# Generated by Django 3.0.5 on 2021-06-23 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('shortname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Abréviation')),
                ('cycle', models.CharField(choices=[('c1', 'Cycle 1'), ('c2', 'Cycle 2'), ('c3', 'Cycle 3'), ('c4', 'Cycle 4'), ('c5', 'Cycle 5')], default='c1', max_length=10, verbose_name='Cycle')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('ranking', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('color', models.CharField(default='', editable=False, max_length=255)),
                ('shortname', models.CharField(default='', max_length=10, verbose_name='Abréviation')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('slug', models.CharField(default='', editable=False, max_length=255)),
                ('subject', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='theme', to='socle.Subject', verbose_name='Enseignement')),
            ],
        ),
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nom')),
                ('level', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='waitings', to='socle.Level', verbose_name='Niveau')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitings', to='socle.Theme', verbose_name='Thème')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='Nom')),
                ('subject', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skill', to='socle.Subject', verbose_name='Enseignement')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='themes',
            field=models.ManyToManyField(default='', related_name='theme_level', to='socle.Theme', verbose_name='Thèmes'),
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='Nom')),
                ('level', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='knowledges', to='socle.Level', verbose_name='Niveau')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledges', to='socle.Theme', verbose_name='Thème')),
                ('waiting', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledges', to='socle.Waiting', verbose_name='Attendu')),
            ],
        ),
    ]
