# Generated by Django 3.0.5 on 2021-09-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='cycle',
            field=models.CharField(choices=[('c1', 'Cycle 1'), ('c2', 'Cycle 2'), ('c3', 'Cycle 3'), ('c4', 'Cycle 4'), ('c5', 'Cycle 5'), ('c6', 'Post BaC')], default='c1', max_length=10, verbose_name='Cycle'),
        ),
    ]
