# Generated by Django 3.0.5 on 2021-09-30 07:20

from django.db import migrations, models
import socle.models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0002_auto_20210907_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='imagefile',
            field=models.ImageField(blank=True, default='', upload_to=socle.models.directory_path, verbose_name='Vignette'),
        ),
    ]
