# Generated by Django 3.0.5 on 2021-09-30 11:37

from django.db import migrations, models
import django.db.models.deletion
import socle.models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0003_subject_imagefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vignette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('imagefile', models.ImageField(upload_to=socle.models.directory_path, verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='imagefile',
        ),
        migrations.CreateModel(
            name='Vignettesubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.PositiveIntegerField(default=0, editable=False)),
                ('level', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='level_vignettesubject', to='socle.Level')),
                ('subject', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_vignettesubject', to='socle.Subject')),
                ('vignette', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vignette_vignettesubject', to='socle.Vignette')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='vignettes',
            field=models.ManyToManyField(blank=True, related_name='vignettes_subject', through='socle.Vignettesubject', to='socle.Vignette'),
        ),
    ]
