# Generated by Django 3.0.5 on 2021-10-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0004_auto_20210930_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='vignettes',
        ),
        migrations.RemoveField(
            model_name='vignette',
            name='name',
        ),
        migrations.AddField(
            model_name='vignette',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_vignettesubject', to='socle.Level', verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='vignette',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_vignettesubject', to='socle.Subject', verbose_name='Enseignement'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(default='', max_length=255, verbose_name='Couleur'),
        ),
        migrations.DeleteModel(
            name='Vignettesubject',
        ),
    ]
