# Generated by Django 3.0.5 on 2021-10-06 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0005_auto_20211006_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vignette',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vignettes', to='socle.Level', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vignettes', to='socle.Subject', verbose_name='Enseignement'),
        ),
    ]
