# Generated by Django 3.0.5 on 2021-06-28 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('qcm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testhistoric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clone', models.ForeignKey(blank=True, default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='clone_to_test', to='qcm.Parcours')),
                ('origin', models.ForeignKey(blank=True, default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='origin_to_test', to='qcm.Parcours')),
                ('teacher', models.ForeignKey(blank=True, default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='clone_to_test', to='account.Teacher')),
            ],
        ),
    ]
