# Generated by Django 3.0.5 on 2021-06-28 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('aefe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testhistoric',
            name='teacher',
            field=models.ForeignKey(blank=True, default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_to_test', to='account.Teacher'),
        ),
    ]
