# Generated by Django 3.0.5 on 2021-10-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtex',
            name='is_print',
            field=models.BooleanField(default=0, verbose_name='Imprimé ?'),
        ),
    ]
