# Generated by Django 3.0.5 on 2021-10-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0002_relationtex_is_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='exotex',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='relationtex',
            unique_together={('exotex', 'bibliotex')},
        ),
    ]
