# Generated by Django 3.0.5 on 2021-10-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0003_auto_20211015_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationtex',
            old_name='content_cor',
            new_name='correction',
        ),
    ]
