# Generated by Django 3.0.5 on 2021-10-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0004_auto_20211015_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtex',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Enoncé en LaTeX'),
        ),
    ]
