# Generated by Django 3.0.5 on 2021-10-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_teacher_helping'),
        ('bibliotex', '0005_relationtex_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklistex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationtex', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='blacklistex', to='bibliotex.Exotex')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='blacklistex', to='account.Student')),
            ],
        ),
    ]
