# Generated by Django 3.0.5 on 2021-10-17 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0006_blacklistex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistex',
            name='relationtex',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='blacklistex', to='bibliotex.Relationtex'),
        ),
    ]
