# Generated by Django 3.0.5 on 2021-10-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0016_auto_20211002_1650'),
        ('bibliotex', '0007_auto_20211017_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliotex',
            name='parcours',
            field=models.ManyToManyField(blank=True, related_name='bibliotexs', to='qcm.Parcours'),
        ),
    ]
