# Generated by Django 3.0.5 on 2021-10-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0009_bibliotex_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='exotex',
            name='content_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
