# Generated by Django 3.0.5 on 2021-11-22 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0006_auto_20211006_2229'),
        ('bibliotex', '0011_auto_20211105_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='exotex',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subject_exotexs', to='socle.Subject', verbose_name='Enseignement associé'),
        ),
    ]
