# Generated by Django 3.0.5 on 2021-12-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0012_exotex_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtex',
            name='content_html',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='relationtex',
            name='correction_html',
            field=models.TextField(blank=True, default='', editable=False, null=True),
        ),
    ]
