# Generated by Django 3.0.5 on 2021-12-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0013_auto_20211205_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='exotex',
            name='is_tableur',
            field=models.BooleanField(default=0, verbose_name='Tableur ?'),
        ),
    ]
