# Generated by Django 3.0.5 on 2021-12-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0014_exotex_is_tableur'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtex',
            name='is_tableur',
            field=models.BooleanField(default=0, verbose_name='Tableur ?'),
        ),
    ]
