# Generated by Django 3.0.5 on 2022-02-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0015_relationtex_is_tableur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exotex',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Titre'),
        ),
    ]
