# Generated by Django 3.0.5 on 2022-02-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0006_auto_20211006_2229'),
        ('bibliotex', '0016_auto_20220209_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exotex',
            name='knowledges',
            field=models.ManyToManyField(blank=True, default='', related_name='other_knowledge_exotexs', to='socle.Knowledge', verbose_name='Savoir faire associés complémentaires'),
        ),
    ]
